version: "3.8"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_mongo_data: {}

services:
  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sportfy_production_postgres
    deploy:
      resources:
        limits:
          memory: 300M
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file: ./.env
    ports:
      - "5432:5432"
    container_name: postgres

  mongodb:
    image: mongo:latest
    volumes:
      - local_mongo_data:/data/db
    env_file: ./.env
    ports:
      - '27017:27017'
    container_name: mongodb

  redis:
    image: redis:7.0.11-alpine
    deploy:
      resources:
        limits:
          memory: 200M
    container_name: redis

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ludushub_local_django
    volumes:
      - ./web-1:/web-1
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 200M
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: /start
    container_name: django

  celeryworker:
    <<: *django
    image: ludushub_local_celeryworker
    volumes:
      - ./web-1:/web-1
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 300M
    ports: []
    depends_on:
      - redis
      - django
    command: /start-celeryworker
    container_name: celeryworker

  fastapi:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    volumes:
      - ./web-2:/web-2
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          memory: 200M
    ports:
      - "8001:8001"
    command: /start
    container_name: fastapi
