# Generated by Django 4.1.4 on 2023-05-06 05:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modality',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name', unique_with=['name']),
        ),
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name', unique_with=['name']),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name', unique_with=['name']),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name', unique_with=['name']),
        ),
    ]
