# Generated by Django 4.1.4 on 2023-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_category_modality_tag_sport_category_modality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='categories',
            field=models.ManyToManyField(blank=True, to='sports.category'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='tags',
            field=models.ManyToManyField(blank=True, to='sports.tag'),
        ),
    ]
