# Generated by Django 4.1.4 on 2023-04-22 18:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_alter_sport_categories_alter_sport_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='modality',
            options={'verbose_name_plural': 'Modalities'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='name', unique_with=['name', 'gender', 'modality']),
        ),
        migrations.AlterField(
            model_name='modality',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name'),
        ),
    ]
