# Generated by Django 4.2.1 on 2023-05-10 02:43

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0004_alter_modality_slug_alter_sport_slug_alter_tag_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.category')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.team')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('all_play_all', 'All Play All'), ('single_elimination', 'Single Elimination'), ('single_elimination_playoff', 'Single Elimination Playoff'), ('double_elimination', 'Double Elimination')], max_length=26)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.category')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('group', 'Group'), ('versus', 'Versus')], max_length=6)),
                ('state', models.CharField(choices=[('scheduled', 'Scheduled'), ('playing', 'Playing'), ('paused', 'Paused')], max_length=9)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('type', models.CharField(choices=[('all_play_all', 'All Play All'), ('single_elimination', 'Single Elimination'), ('single_elimination_playoff', 'Single Elimination Playoff'), ('double_elimination', 'Double Elimination')], max_length=26)),
                ('level', models.CharField(choices=[('group', 'Group'), ('playoff', 'Playoff'), ('semifinal', 'Semifinal'), ('bronze', 'Bronze'), ('final', 'Final')], max_length=9)),
                ('order', models.SmallIntegerField(default=1)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.draw')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=150, populate_from='name', unique_with=['name'])),
                ('type', models.CharField(choices=[('open', 'Open'), ('qualifying', 'Qualifying'), ('ranking', 'Ranking'), ('shampionship', 'Shampionship')], max_length=12)),
                ('level', models.CharField(choices=[('local', 'local'), ('departmental', 'departmental'), ('national', 'national'), ('international', 'international')], max_length=13)),
                ('description', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('date', models.DateTimeField()),
                ('categories', models.ManyToManyField(blank=True, to='sports.category')),
                ('referees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sports.sport')),
            ],
            options={
                'ordering': ['-created', '-updated', 'name'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoundMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.SmallIntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.match')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.round')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='round',
            name='matches',
            field=models.ManyToManyField(through='sports.RoundMatch', to='sports.match'),
        ),
        migrations.AddField(
            model_name='round',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sports.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sports.tournament'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('score', models.FloatField()),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.competitor')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchCompetitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.SmallIntegerField(default=1)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.competitor')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.match')),
                ('rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.rating')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='match',
            name='competitors',
            field=models.ManyToManyField(through='sports.MatchCompetitor', to='sports.competitor'),
        ),
        migrations.AddField(
            model_name='draw',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sports.tournament'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='tournament',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='sports.tournament'),
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('conditions', models.JSONField(default=dict)),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.modality')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
            ],
            options={
                'unique_together': {('sport', 'modality')},
            },
        ),
    ]
