# Generated by Django 4.2.1 on 2023-05-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_competitor_draw_match_round_tournament_roundmatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='level_type',
            field=models.CharField(choices=[('group', 'Group'), ('playoff', 'Playoff'), ('semifinal', 'Semifinal'), ('bronze', 'Bronze'), ('final', 'Final')], default='playoff', max_length=9),
        ),
        migrations.AlterField(
            model_name='round',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='level',
            field=models.CharField(choices=[('local', 'Local'), ('departmental', 'Departmental'), ('national', 'National'), ('international', 'International')], max_length=13),
        ),
    ]
