# Generated by Django 4.2.1 on 2023-05-22 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0006_round_level_type_alter_round_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.tournament'),
        ),
        migrations.AlterField(
            model_name='round',
            name='level_type',
            field=models.CharField(choices=[('group', 'Group'), ('playoff', 'Playoff'), ('semifinal', 'Semifinal'), ('bronze', 'Bronze'), ('final', 'Final')], default='playoff', max_length=9, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='referees',
            field=models.ManyToManyField(blank=True, related_name='tournaments_as_referee', to=settings.AUTH_USER_MODEL),
        ),
    ]
