# Generated by Django 4.2.1 on 2023-06-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0009_group_remove_round_tournament_match_date_and_more_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='competitor',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='draw',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='groupmatch',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='matchcompetitor',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='roundgroup',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='roundmatch',
            options={'get_latest_by': 'created', 'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'get_latest_by': 'created', 'ordering': ['-created', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'get_latest_by': 'created', 'ordering': ['-created', 'name']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'get_latest_by': 'created', 'ordering': ['-created', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'get_latest_by': 'created', 'ordering': ['-created', 'name']},
        ),
        migrations.AddField(
            model_name='assistance',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
