# Generated by Django 4.2.1 on 2023-06-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0010_alter_club_options_alter_competitor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'Matches Groups'},
        ),
        migrations.AlterModelOptions(
            name='groupmatch',
            options={'verbose_name': 'Match Group'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='roundgroup',
            options={'verbose_name': 'Matches Group'},
        ),
        migrations.AlterModelOptions(
            name='roundmatch',
            options={'verbose_name': 'Match'},
        ),
    ]
