# Generated by Django 4.2.1 on 2023-06-23 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_alter_group_options_alter_groupmatch_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
