# Generated by Django 4.2.1 on 2023-07-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_rename_rules_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team')], default='individual', max_length=10),
        ),
    ]
