# Generated by Django 4.2.1 on 2023-08-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0013_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='type',
            field=models.CharField(choices=[('all_play_all', 'All Play All'), ('single_elimination', 'Single Elimination'), ('single_elimination_playoff', 'Single Elimination Playoff'), ('double_elimination', 'Double Elimination'), ('group_stage_and_playoffs', 'Group Stage and Playoffs')], max_length=26),
        ),
        migrations.AlterField(
            model_name='match',
            name='state',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('playing', 'Playing'), ('paused', 'Paused'), ('finished', 'Finished')], max_length=9),
        ),
    ]
