# Generated by Django 4.2.1 on 2023-08-26 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0014_alter_draw_type_alter_match_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='tournaments_as_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RefereeInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('used', models.BooleanField(default=False)),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referee_invitations', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='referee_invitations',
            field=models.ManyToManyField(blank=True, to='sports.refereeinvitation'),
        ),
    ]
