# Generated by Django 4.1.4 on 2023-04-24 04:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stripe_id', models.CharField(max_length=100, unique=True)),
                ('last4', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='last4 number must be 4 digits.', regex='^\\d{4}$')])),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stripe_id', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(choices=[('cop', 'COP'), ('usd', 'USD')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('stripe_id', models.CharField(max_length=100, unique=True)),
                ('product_id', models.CharField(max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=7)),
                ('description', models.TextField(blank=True, max_length=300)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.price')),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
