# Generated by Django 4.1.4 on 2023-04-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
