# Generated by Django 4.1.2 on 2022-10-26 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('photo', models.ImageField(blank=True, help_text='profile photo', null=True, upload_to='users/photos/%Y/%m/%d/')),
                ('cover_photo', models.ImageField(blank=True, help_text='profile cover photo', null=True, upload_to='users/cover_photos/%Y/%m/%d/')),
                ('about', models.TextField(blank=True, help_text='write something about you')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('sport', models.CharField(blank=True, help_text='What sport do you play?', max_length=25)),
                ('country', models.CharField(blank=True, help_text='your country of origin', max_length=60)),
                ('public', models.BooleanField(default=True, help_text='Profile privacy')),
                ('web_site', models.URLField(blank=True, help_text='personal web site')),
                ('social_link', models.URLField(blank=True, help_text='social media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-updated'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
