# Generated by Django 4.1.2 on 2022-11-18 03:10

import apps.utils.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='profile cover photo', null=True, upload_to=apps.utils.files.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, help_text='profile photo', null=True, upload_to=apps.utils.files.user_directory_path),
        ),
    ]
